Nama = str(input("Siapa namamu? = "))
Umur = int(input("Berapa umurmu? = "))
Tinggi = float(input("Berapa tinggimu? = "))
Teks = "Nama saya {}, Umur saya {} tahun dan tinggi saya {} cm".format (Nama, Umur, Tinggi)
print (Teks)